name: build-my-yuedu

on: 
  release:
    types: [published]
  push:
    tags:
    - '3.*'
  watch:
    types: [started]
  #schedule:
  #  - cron: '0 4 * * *'
      
env:
  REPO_URL: https://github.com/gedoor/legado.git

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clone source code
      run: git clone $REPO_URL yuedu
      
    - name: clear 18PlusList.txt
      run: |
        echo "清空18PlusList.txt"
        echo "">yuedu/app/src/main/assets/18PlusList.txt
    - name: release apk sign
      run: |
        echo "给apk增加签名"
        cp yuedu/.github/workflows/legado.jks yuedu/app/legado.jks
        sed '$a\RELEASE_STORE_FILE=./legado.jks'          yuedu/gradle.properties -i
        sed '$a\RELEASE_KEY_ALIAS=legado'                 yuedu/gradle.properties -i
        sed '$a\RELEASE_STORE_PASSWORD=gedoor_legado'     yuedu/gradle.properties -i
        sed '$a\RELEASE_KEY_PASSWORD=gedoor_legado'       yuedu/gradle.properties -i
    #- name: apk live together
    #  run: |
    #    echo "设置apk共存"
    #    sed -i "s/'.release'/'.releaseA'/" yuedu/app/build.gradle 
    #    sed-i 's/.release/.releaseA/'     yuedu/app/google-services.json 
    - name: build with gradle
      run: |
        cd yuedu
        echo "开始进行release构建"
        chmod +x gradlew
        ./gradlew assembleAppRelease
    - name : upload apk
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: YueDu
        path: yuedu/app/build/outputs/apk/app/release
